questions =  [
	{"id": 0, "question": "It is immoral for a country to invade and/or claim another land for resources.", "effects": {"is": -1}, "type": "default"},
    {"id": 1, "question": "Many of the colonized benefited from colonialism.", "effects": {"is": 1}, "type": "default"},
    {"id": 2, "question": "People should be treated equally, regardless of race, gender, or creed.", "effects": {"is": -1}, "type": "default"},
    {"id": 3, "question": "Races are scientific reality.", "effects": {"is": 1}, "type": "default"},
    {"id": 4, "question": "There is racial inequality in society that disadvantages certain groups, and we should address it.", "effects": {"is": -1}, "type": "default"},
    {"id": 5, "question": "Fundamentally, our society is sexist and patriarchal, and this is a bad thing.", "effects": {"is": -2}, "type": "default"},
    {"id": 6, "question": "Abortion should be legal in all circumstances.", "effects": {"is": -1}, "type": "default"},
    {"id": 7, "question": "Gender is a social construct, not a natural state of affairs.", "effects": {"is": -1}, "type": "default"},
    {"id": 8, "question": "How many genders are there?", "effects": {"is": -1}, "type": "gendernumbers"},
    {"id": 9, "question": "Transgender people are the gender they say they are.", "effects": {"is": -1}, "type": "default"},
    {"id": 10, "question": "Men should hold a position of power over women in society.", "effects": {"is": 1}, "type": "default"},
    {"id": 11, "question": "Gender should be abolished.", "effects": {"is": -1}, "type": "default"},
    {"id": 12, "question": "Neopronouns or xenogenders aren't legitimate.", "effects": {"is": 1}, "type": "default"},
    {"id": 13, "question": "The family should be abolished.", "effects": {"is": -1}, "type": "default"},
    {"id": 14, "question": "The family is the most important unit in society.", "effects": {"is": -1}, "type": "default"},
    {"id": 15, "question": "Parents should hold absolute power over their children, as they are older and more experienced.", "effects": {"is": 1}, "type": "default"},
    {"id": 16, "question": "Borders and nation-states should be abolished.", "effects": {"is": -1}, "type": "default"},
    {"id": 17, "question": "Deportation is legitimate, even if no crime other than overstaying a visa has been committed.", "effects": {"is": 1}, "type": "default"},
    {"id": 18, "question": "We should keep all sovereignty at the national level, rather than granting powers to organizations like the EU or UN.", "effects": {"is": 1}, "type": "default"},
    {"id": 19, "question": "It is a state's right to enforce unity of culture and language.", "effects": {"is": 1}, "type": "default"},
    {"id": 20, "question": "No-one is illegal on stolen land.", "effects": {"is": -1}, "type": "default"},
    {"id": 21, "question": "The presence of another culture is no threat to my own.", "effects": {"is": -1}, "type": "default"},
    {"id": 22, "question": "Homosexuality is against my values.", "effects": {"is": 1}, "type": "default"},
    {"id": 23, "question": "We shouldn't expose children to gay or transgender people until they're older.", "effects": {"is": 1}, "type": "default"},
    {"id": 24, "question": "Animals deserve certain universal rights.", "effects": {"is": -1}, "type": "default"},
    {"id": 25, "question": "To eat meat is morally wrong.", "effects": {"is": -1}, "type": "default"},
    {"id": 26, "question": "The death penalty should exist for certain crimes.", "effects": {"is": 1}, "type": "default"},
    {"id": 27, "question": "A strong hierarchy is desirable in a society.", "effects": {"is": 2}, "type": "default"},
    {"id": 28, "question": "I am fine with police and government forces using violence against unarmed civilians.", "effects": {"is": 1}, "type": "default"},
    {"id": 29, "question": "We should end programs that support diversity, equity, and inclusion in business and government.", "effects": {"is": 1}, "type": "default"},
    {"id": 30, "question": "It's acceptable to make fun of someone based on their appearance.", "effects": {"acts": 1}, "type": "default"},
    {"id": 31, "question": "It's acceptable to make fun of someone based on their identity.", "effects": {"acts": 1}, "type": "default"},
    {"id": 32, "question": "It's acceptable to make fun of generalized groups.", "effects": {"acts": 1}, "type": "default"},
    {"id": 33, "question": "I think it's particularly offensive for people to say slurs.", "effects": {"acts": -1}, "type": "default"},
    {"id": 34, "question": "Telling somebody to kill themselves crosses a line.", "effects": {"acts": -1}, "type": "default"},
    {"id": 35, "question": "Online harassment or cancellation is a serious issue.", "effects": {"acts": -2}, "type": "default"},
    {"id": 36, "question": "People describe me as...", "effects": {"acts": 4}, "type": "behavedescription"},
    {"id": 37, "question": "(Women only) I dress...", "effects": {"acts": 1}, "type": "womandress"},
    {"id": 38, "question": "(Women only) My hair is...", "effects": {"acts": -1}, "type": "womanhair"},
    {"id": 39, "question": "(Men only) I have...", "effects": {"acts": 1}, "type": "manhair"},
    {"id": 40, "question": "(Men only) I have...", "effects": {"acts": 1}, "type": "manwomenfriends"},
    {"id": 40, "question": "(Non-binary only) My name is...", "effects": {"acts": 2}, "type": "nbname"},
    {"id": 41, "question": "My hair is dyed.", "effects": {"acts": -1}, "type": "dyedhair"},
    {"id": 42, "question": "I am publicly out as LGBT.", "effects": {"acts": -1}, "type": "default"},
    {"id": 43, "question": "I celebrate, or strongly support, Pride Month.", "effects": {"acts": -1}, "type": "default"},
    {"id": 44, "question": "I am waiting until marriage for sex.", "effects": {"acts": 1}, "type": "default"},
    {"id": 45, "question": "My romantic partner is...", "effects": {"acts": 1}, "type": "partner"},
    {"id": 46, "question": "I read contemporary philosophers.", "effects": {"acts": -1}, "type": "default"},
    {"id": 47, "question": "I prefer...", "effects": {"acts": -1}, "type": "cityvsrural"},
    {"id": 48, "question": "I put pronouns in my bio.", "effects": {"acts": -1}, "type": "default"},
    {"id": 49, "question": "I am...", "effects": {"acts": 1}, "type": "religion"},
    {"id": 50, "question": "If entertainment media or commercials have a certain identity makeup, whether that be a lack of diversity or forced diversity, that upsets me.", "effects": {"acts": -1}, "type": "default"},
    {"id": 51, "question": "There are some words or phrases people should be punished for using.", "effects": {"acts": -1}, "type": "default"},
    {"id": 52, "question": "I like anime.", "effects": {"acts": -1}, "type": "default"},
    {"id": 53, "question": "I have compared real life political events to mainstream entertainment, such as Star Wars, Anime, or Harry Potter.", "effects": {"acts": -1}, "type": "default"},
    {"id": 54, "question": "It's good when companies publicly support progressive social causes.", "effects": {"acts": -1}, "type": "default"},
    {"id": 55, "question": "I like offending people, and intentionally say provocative things.", "effects": {"acts": 1}, "type": "default"},
    {"id": 56, "question": "I support doing land acknowledgements.", "effects": {"acts": -1}, "type": "default"},
    {"id": 57, "question": "My country or people should apologize for crimes and wrongdoing our ancestors have committed.", "effects": {"acts": -1}, "type": "default"},
    {"id": 58, "question": "I respect people's neopronouns or xenogenders.", "effects": {"acts": -1}, "type": "default"}, 
];
