questions =  [
	{"id": 0, "question": "Colonialism is bad.", "effects": {"is": -1}, "type": "default"},
    {"id": 1, "question": "Apologise for Colonialism.", "effects": {"is": -1}, "type": "default"},
    {"id": 2, "question": "The colonized benefited from Colonialism.", "effects": {"is": 1}, "type": "default"},
    {"id": 3, "question": "Racism is bad.", "effects": {"is": -1}, "type": "default"},
    {"id": 4, "question": "Races are real.", "effects": {"is": 1}, "type": "default"},
    {"id": 5, "question": "Racism should be addressed.", "effects": {"is": -1}, "type": "default"},
    {"id": 6, "question": "Fundamentally, our society is sexist and patriarchal.", "effects": {"is": -1}, "type": "default"},
    {"id": 7, "question": "Abortion should be legal.", "effects": {"is": -1}, "type": "default"},
    {"id": 8, "question": "Gender is a social construct, not a natural state of affairs.", "effects": {"is": -1}, "type": "default"},
    {"id": 9, "question": "How many genders are there?", "effects": {"is": -1}, "type": "gendernumbers"},
    {"id": 10, "question": "Transgender people are the gender they say they are.", "effects": {"is": -1}, "type": "default"},
    {"id": 11, "question": "Men should hold a position of power over women in society.", "effects": {"is": 1}, "type": "default"},
    {"id": 12, "question": "Gender should be abolished.", "effects": {"is": -1}, "type": "default"},
    {"id": 13, "question": "The family should be abolished.", "effects": {"is": -1}, "type": "default"},
    {"id": 14, "question": "Parents should hold absolute power over their children, as they are older and more experienced.", "effects": {"is": 1}, "type": "default"},
    {"id": 15, "question": "Nationalism bad.", "effects": {"is": -1}, "type": "default"},
    {"id": 16, "question": "Nationalism good.", "effects": {"is": 1}, "type": "default"},
    {"id": 17, "question": "Globalism bad.", "effects": {"is": 1}, "type": "default"},
    {"id": 18, "question": "Globalism good.", "effects": {"is": -1}, "type": "default"},
    {"id": 19, "question": "Animals deserve certain universal rights.", "effects": {"is": 1}, "type": "default"},
    {"id": 20, "question": "The death penalty should exist for certain crimes.", "effects": {"is": 1}, "type": "default"},
    {"id": 21, "question": "Homosexuality is against my values.", "effects": {"is": 1}, "type": "default"},
    {"id": 22, "question": "Homosexuality is against my values.", "effects": {"is": 1}, "type": "default"},
    {"id": 23, "question": "A strong hierarchy is desirable in a society.", "effects": {"is": 1}, "type": "default"},
    {"id": 24, "question": "It's acceptable to make fun of someone based on their appearance.", "effects": {"acts": 1}, "type": "default"},
    {"id": 25, "question": "It's acceptable to make fun of someone based on their identity.", "effects": {"acts": 1}, "type": "default"},
    {"id": 26, "question": "It's acceptable to make fun of generalized groups.", "effects": {"acts": 1}, "type": "default"},
    {"id": 27, "question": "I think it's particularly offensive for people to say slurs.", "effects": {"acts": -1}, "type": "default"},
    {"id": 28, "question": "People describe me as...", "effects": {"acts": 1}, "type": "behavedescription"},
    {"id": 29, "question": "(Women only) I dress...", "effects": {"acts": 1}, "type": "womandress"},
    {"id": 30, "question": "(Women only) My hair is...", "effects": {"acts": 1}, "type": "womanhair"},
    {"id": 31, "question": "(Men only) I have...", "effects": {"acts": 1}, "type": "manhair"},
    {"id": 32, "question": "(Men only) I have...", "effects": {"acts": 1}, "type": "manwomenfriends"},
    {"id": 33, "question": "My hair is dyed.", "effects": {"acts": -1}, "type": "dyedhair"},
    {"id": 34, "question": "I prefer...", "effects": {"acts": -1}, "type": "cityvsrural"},
    {"id": 35, "question": "I put pronouns in my bio.", "effects": {"acts": -1}, "type": "default"},
    {"id": 36, "question": "I support doing land acknowledgements.", "effects": {"acts": -1}, "type": "default"},
    {"id": 37, "question": "Neopronouns are good.", "effects": {"acts": -1}, "type": "default"},
    {"id": 38, "question": "Xenogenders are silly.", "effects": {"acts": 1}, "type": "default"},
    {"id": 39, "question": "I am...", "effects": {"acts": 1}, "type": "religion"},
];
