questions =  [
    {"id": 0, "question": "Big Chungus.", "effects": {"is": 1}, "type": "default"},
    {"id": 1, "question": "Charity is a better way of helping those in need than social welfare.", "effects": {"is": 1}, "type": "default"},
    {"id": 2, "question": "Wages are always fair, as employers know best what a worker's labour is worth.", "effects": {"is": 1}, "type": "default"},
    {"id": 3, "question": "It is \"human nature\" to be greedy.", "effects": {"is": 1}, "type": "default"},
    {"id": 4, "question": "\"Exploitation\" is an outdated term, as the struggles of 1800s capitalism don't exist anymore.", "effects": {"is": 1}, "type": "default"},
    {"id": 5, "question": "Communism is an ideal that can never work in practice.", "effects": {"is": 1}, "type": "default"},
    {"id": 6, "question": "Taxation of the wealthy is a bad idea, society would be better off without it.", "effects": {"is": 1}, "type": "default"},
    {"id": 7, "question": "The harder you work, the more you progress up the social ladder.", "effects": {"is": 1}, "type": "default"},
    {"id": 8, "question": "Organisations and corporations cannot be trusted and need to be regulated by the government.", "effects": {"is": -1}, "type": "default"},
    {"id": 9, "question": "A government that provides for everyone is an inherently good idea.", "effects": {"is": -1}, "type": "default"},
    {"id": 10, "question": "The current welfare system should be expanded to further combat inequality.", "effects": {"is": -1}, "type": "default"},
    {"id": 11, "question": "Land should not be a commodity to be bought and sold.", "effects": {"is": -1}, "type": "default"},
    {"id": 12, "question": "All industry and the bank should be nationalised.", "effects": {"is": -1}, "type": "default"},
    {"id": 13, "question": "Class is the primary division of society.", "effects": {"is": -1}, "type": "default"},
    {"id": 14, "question": "Economic inequality is too high in the world.", "effects": {"is": -1}, "type": "default"},
    {"id": 15, "question": "Sometimes it is right that the government may spy on its citizens to combat extremists and terrorists.", "effects": {"acts": 1}, "type": "default"},
    {"id": 16, "question": "Authority figures, if morally correct, are a good thing for society.", "effects": {"acts": 1}, "type": "default"},
    {"id": 17, "question": "Strength is necessary for any government to succeed.", "effects": {"acts": 1}, "type": "default"},
    {"id": 18, "question": "Only the government can fairly and effectively regulate organisations.", "effects": {"acts": 1}, "type": "default"},
    {"id": 19, "question": "Society requires structure and bureaucracy in order to function.", "effects": {"acts": 1}, "type": "default"},
    {"id": 20, "question": "Mandatory IDs should be used to ensure public safety.", "effects": {"acts": 1}, "type": "default"},
    {"id": 21, "question": "In times of crisis, safety becomes more important than civil liberties.", "effects": {"acts": 1}, "type": "default"},
    {"id": 22, "question": "If you have nothing to hide, you have nothing to fear.", "effects": {"acts": 1}, "type": "default"},
    {"id": 23, "question": "The government should be less involved in the day to day life of its citizens.", "effects": {"acts": -1}, "type": "default"},
    {"id": 24, "question": "Without democracy, a society is nothing.", "effects": {"acts": -1}, "type": "default"},
    {"id": 25, "question": "Jury nullification should be legal.", "effects": {"acts": -1}, "type": "default"},
    {"id": 26, "question": "The smaller the government, the freer the people.", "effects": {"acts": -1}, "type": "default"},
    {"id": 27, "question": "The government should, at most, provide emergency services and law enforcement.", "effects": {"acts": -1}, "type": "default"},
    {"id": 28, "question": "The police were not created to protect the people, but to uphold the status quo by force.", "effects": {"acts": -1}, "type": "default"},
    {"id": 29, "question": "State schools are a bad idea because our state shouldn't be influencing our children.", "effects": {"acts": -1}, "type": "default"},
    {"id": 30, "question": "Two consenting individuals should be able to do whatever they want with each other, even if it makes me uncomfortable.", "effects": {"prog": 1}, "type": "default"},
    {"id": 31, "question": "An individual's body is their own property, and they should be able to do anything they desire to it.", "effects": {"prog": 1}, "type": "default"},
    {"id": 32, "question": "A person should be able to worship whomever or whatever they want.", "effects": {"prog": 1}, "type": "default"},
    {"id": 33, "question": "Nudism is perfectly natural.", "effects": {"prog": 1}, "type": "default"},
    {"id": 34, "question": "Animals deserve certain universal rights.", "effects": {"prog": 1}, "type": "default"},
    {"id": 35, "question": "Gender is a social construct, not a natural state of affairs.", "effects": {"prog": 1}, "type": "default"},
    {"id": 36, "question": "Laws based on cultural values, rather than ethical ones, aren't justice.", "effects": {"prog": 1}, "type": "default"},
    {"id": 37, "question": "Autonomy of body extends even to minors, the mentally ill, and serious criminals.", "effects": {"prog": 1}, "type": "default"},
    {"id": 38, "question": "Homosexuality is against my values.", "effects": {"prog": -1}, "type": "default"},
    {"id": 39, "question": "Transgender individuals should not be able to adopt children.", "effects": {"prog": -1}, "type": "default"},
    {"id": 40, "question": "Drugs are harmful and should be banned.", "effects": {"prog": -1}, "type": "default"},
    {"id": 41, "question": "The death penalty should exist for certain crimes.", "effects": {"prog": -1}, "type": "default"},
    {"id": 42, "question": "Victimless crimes should still be punished.", "effects": {"prog": -1}, "type": "default"},
    {"id": 43, "question": "One cannot be moral without religion.", "effects": {"prog": -1}, "type": "default"},
    {"id": 44, "question": "Parents should hold absolute power over their children, as they are older and more experienced.", "effects": {"prog": -1}, "type": "default"},
    {"id": 45, "question": "Multiculturalism is bad.", "effects": {"prog": -1}, "type": "default"}
];
